/* Gerado por scripts/og_cartas.py. Nome da carta -> pagina de
   compartilhamento com a imagem certa no preview. */
const SLUGS = {
  "O Louco": "o-louco",
  "O Mago": "o-mago",
  "A Sacerdotisa": "a-sacerdotisa",
  "A Imperatriz": "a-imperatriz",
  "O Imperador": "o-imperador",
  "O Hierofante": "o-hierofante",
  "Os Amantes": "os-amantes",
  "O Carro": "o-carro",
  "A Força": "a-forca",
  "O Eremita": "o-eremita",
  "A Roda da Fortuna": "a-roda-da-fortuna",
  "A Justiça": "a-justica",
  "O Enforcado": "o-enforcado",
  "A Morte": "a-morte",
  "A Temperança": "a-temperanca",
  "O Diabo": "o-diabo",
  "A Torre": "a-torre",
  "A Estrela": "a-estrela",
  "A Lua": "a-lua",
  "O Sol": "o-sol",
  "O Julgamento": "o-julgamento",
  "O Mundo": "o-mundo",
  "Ás de Copas": "as-de-copas",
  "Dois de Copas": "dois-de-copas",
  "Três de Copas": "tres-de-copas",
  "Quatro de Copas": "quatro-de-copas",
  "Cinco de Copas": "cinco-de-copas",
  "Seis de Copas": "seis-de-copas",
  "Sete de Copas": "sete-de-copas",
  "Oito de Copas": "oito-de-copas",
  "Nove de Copas": "nove-de-copas",
  "Dez de Copas": "dez-de-copas",
  "Valete de Copas": "valete-de-copas",
  "Cavaleiro de Copas": "cavaleiro-de-copas",
  "Rainha de Copas": "rainha-de-copas",
  "Rei de Copas": "rei-de-copas",
  "Ás de Ouros": "as-de-ouros",
  "Dois de Ouros": "dois-de-ouros",
  "Três de Ouros": "tres-de-ouros",
  "Quatro de Ouros": "quatro-de-ouros",
  "Cinco de Ouros": "cinco-de-ouros",
  "Seis de Ouros": "seis-de-ouros",
  "Sete de Ouros": "sete-de-ouros",
  "Oito de Ouros": "oito-de-ouros",
  "Nove de Ouros": "nove-de-ouros",
  "Dez de Ouros": "dez-de-ouros",
  "Valete de Ouros": "valete-de-ouros",
  "Cavaleiro de Ouros": "cavaleiro-de-ouros",
  "Rainha de Ouros": "rainha-de-ouros",
  "Rei de Ouros": "rei-de-ouros",
  "Ás de Espadas": "as-de-espadas",
  "Dois de Espadas": "dois-de-espadas",
  "Três de Espadas": "tres-de-espadas",
  "Quatro de Espadas": "quatro-de-espadas",
  "Cinco de Espadas": "cinco-de-espadas",
  "Seis de Espadas": "seis-de-espadas",
  "Sete de Espadas": "sete-de-espadas",
  "Oito de Espadas": "oito-de-espadas",
  "Nove de Espadas": "nove-de-espadas",
  "Dez de Espadas": "dez-de-espadas",
  "Valete de Espadas": "valete-de-espadas",
  "Cavaleiro de Espadas": "cavaleiro-de-espadas",
  "Rainha de Espadas": "rainha-de-espadas",
  "Rei de Espadas": "rei-de-espadas",
  "Ás de Paus": "as-de-paus",
  "Dois de Paus": "dois-de-paus",
  "Três de Paus": "tres-de-paus",
  "Quatro de Paus": "quatro-de-paus",
  "Cinco de Paus": "cinco-de-paus",
  "Seis de Paus": "seis-de-paus",
  "Sete de Paus": "sete-de-paus",
  "Oito de Paus": "oito-de-paus",
  "Nove de Paus": "nove-de-paus",
  "Dez de Paus": "dez-de-paus",
  "Valete de Paus": "valete-de-paus",
  "Cavaleiro de Paus": "cavaleiro-de-paus",
  "Rainha de Paus": "rainha-de-paus",
  "Rei de Paus": "rei-de-paus"
};
